CREATE TABLE video_files(path TEXT PRIMARY KEY,genre TEXT,title TEXT,f_type TEXT,playcount INTEGER,length INTEGER,lastplayed INTEGER);


INSERT INTO video_files VALUES('/cifs/ent-videos/tv/farscape/s01e02a.mkv','farscape','s01e02a','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/farscape/s01e06.mkv','farscape','s01e06','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e01.saa.mkv','robot chicken','robot chicken s02e01 saa','video',1,0,1225580536);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e02.saa.mkv','robot chicken','robot chicken s02e02 saa','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e03.saa.mkv','robot chicken','robot chicken s02e03 saa','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e04.saa.mkv','robot chicken','robot chicken s02e04 saa','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e05.saa.mkv','robot chicken','robot chicken s02e05 saa','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e06.saa.mkv','robot chicken','robot chicken s02e06 saa','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e07.saa.mkv','robot chicken','robot chicken s02e07 saa','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e08.saa.mkv','robot chicken','robot chicken s02e08 saa','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e09.saa.mkv','robot chicken','robot chicken s02e09 saa','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e10.saa.mkv','robot chicken','robot chicken s02e10 saa','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e11.[saa].mkv','robot chicken','robot chicken s02e11 [saa]','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e12.[saa].mkv','robot chicken','robot chicken s02e12 [saa]','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e13.[saa].mkv','robot chicken','robot chicken s02e13 [saa]','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e14.[saa].mkv','robot chicken','robot chicken s02e14 [saa]','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e15.[saa].mkv','robot chicken','robot chicken s02e15 [saa]','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e16.[saa].mkv','robot chicken','robot chicken s02e16 [saa]','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e17.[saa].mkv','robot chicken','robot chicken s02e17 [saa]','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e18.[saa].mkv','robot chicken','robot chicken s02e18 [saa]','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e19.[saa].mkv','robot chicken','robot chicken s02e19 [saa]','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/robot.chicken/robot.chicken.s02e20.[saa].mkv','robot chicken','robot chicken s02e20 [saa]','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/GHOST_IN_THE_SHELL/02.testation.vob','GHOST IN THE SHELL','02 testation','video',3,0,1219816160);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/GHOST_IN_THE_SHELL/03.android_and_i.vob','GHOST IN THE SHELL','03 android and i','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/GHOST_IN_THE_SHELL/04.intercepter.vob','GHOST IN THE SHELL','04 intercepter','video',2,0,1219815840);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/sga-s02e17.coup_d''etat.vob','STARGATE ATLANTIS S2 D5','sga-s02e17 coup d''etat','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/sga-s02e18.michael.vob','STARGATE ATLANTIS S2 D5','sga-s02e18 michael','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_SEASON_3_D4_US/VIDEO_TS/VTS_10_1.VOB','STARGATE ATLANTIS SEASON 3 D4 US','VTS 10 1','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/gone.in.60.seconds.vob','vobs','gone in 60 seconds','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/hackers.vob','vobs','hackers','video',2,0,1228546337);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/rod.vob','vobs','rod','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/the_fifth_element.vob','vobs','the fifth element','video',2,0,1228546186);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/x_men.vob','vobs','x men','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/history_channel/Cities.of.the.Underworld.1x11.Draculas.Underground.DSR.XViD-BiTE.avi','history channel','Cities of the Underworld 1x11 Draculas Underground DSR XViD-BiTE','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/history_channel/Cities.of.the.Underworld.2x04.Viking.Underground.DSR.XViD-BiTE.avi','history channel','Cities of the Underworld 2x04 Viking Underground DSR XViD-BiTE','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/history_channel/Cities.of.the.Underworld.2x06.Maya.Underground.DSR.XViD-BiTE.avi','history channel','Cities of the Underworld 2x06 Maya Underground DSR XViD-BiTE','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/01 - Pilot.avi','x-files','01 - Pilot','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/02 - Deep Throat.avi','x-files','02 - Deep Throat','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/03 - Squeeze.avi','x-files','03 - Squeeze','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/04 - Conduit.avi','x-files','04 - Conduit','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/05 - The Jersey Devil.avi','x-files','05 - The Jersey Devil','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/06 - Shadows.avi','x-files','06 - Shadows','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/07 - Ghost in the Machine.avi','x-files','07 - Ghost in the Machine','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/08 - Ice.avi','x-files','08 - Ice','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/09 - Space.avi','x-files','09 - Space','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/10 - Fallen Angel.avi','x-files','10 - Fallen Angel','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/11 - Eve.avi','x-files','11 - Eve','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/12 - Free.avi','x-files','12 - Free','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/13 - Beyond the Sea.avi','x-files','13 - Beyond the Sea','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/14 - Gender Bender.avi','x-files','14 - Gender Bender','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/15 - Lazarus.avi','x-files','15 - Lazarus','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/16 - Young at Heart.avi','x-files','16 - Young at Heart','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/17 - E.B.E..avi','x-files','17 - E B E ','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/18 - Miracle Man.avi','x-files','18 - Miracle Man','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/19 - Shapes.avi','x-files','19 - Shapes','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/20 - Darkness Falls.avi','x-files','20 - Darkness Falls','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/21 - Tooms.avi','x-files','21 - Tooms','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/22 - Born Again.avi','x-files','22 - Born Again','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/23 - Roland.avi','x-files','23 - Roland','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/X-Files_xvid/01/24 - The Erlenmeyer Flask.avi','x-files','24 - The Erlenmeyer Flask','video',1,0,1222501610);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/Merlin.2008.S01E01.WS.PDTV.XviD-RiVER.avi','tv','Merlin 2008 S01E01 WS PDTV XviD-RiVER','video',1,0,1228704880);
INSERT INTO video_files VALUES('/cifs/ent-videos/tv/Merlin.2008.S01E02.WS.PDTV.XviD-AFFiNiTY.avi','tv','Merlin 2008 S01E02 WS PDTV XviD-AFFiNiTY','video',1,0,1229231157);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S1_D1/stargate.atlantis-s01e13.hot_zone.VOB','STARGATE ATLANTIS S1 D1','stargate atlantis-s01e13 hot zone','video',1,0,1229660695);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S1_D1/stargate.atlantis-s01e14.sanctuary.VOB','STARGATE ATLANTIS S1 D1','stargate atlantis-s01e14 sanctuary','video',1,0,1229664076);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S1_D1/stargate.atlantis-s01e16.the_brotherhood.VOB','STARGATE ATLANTIS S1 D1','stargate atlantis-s01e16 the brotherhood','video',1,0,1229666723);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S1_D1/stargate.atlantis-s01e17.letters_from_pegasus.VOB','STARGATE ATLANTIS S1 D1','stargate atlantis-s01e17 letters from pegasus','video',1,0,1229669750);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S1_D1/stargate.atlantis-s01e18.the_gift.VOB','STARGATE ATLANTIS S1 D1','stargate atlantis-s01e18 the gift','video',1,0,1229672599);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S1_D1/stargate.atlantis-s01e19.the_siege_part_1.VOB','STARGATE ATLANTIS S1 D1','stargate atlantis-s01e19 the siege part 1','video',1,0,1229674065);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S1_D1/stargate.atlantis-s01e20.the_siege_part_2.VOB','STARGATE ATLANTIS S1 D1','stargate atlantis-s01e20 the siege part 2','video',1,0,1229676293);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e01.the_siege_part_3.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e01 the siege part 3','video',1,0,1229748440);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e02.the_intruder.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e02 the intruder','video',1,0,1229750775);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e03.runner.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e03 runner','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e04.duet.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e04 duet','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e05.condemned.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e05 condemned','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e06.trinity.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e06 trinity','video',1,0,1229753148);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e07.instinct.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e07 instinct','video',1,0,1229755740);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e08.conversion.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e08 conversion','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e09.aurora.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e09 aurora','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e10.the_lost_boys.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e10 the lost boys','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e11.the_hive.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e11 the hive','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e12.epiphany.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e12 epiphany','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e13.critical_mass.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e13 critical mass','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e14.grace_under_pressure.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e14 grace under pressure','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e15.the_tower.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e15 the tower','video',0,0,0);
INSERT INTO video_files VALUES('/cifs/ent-videos/vobs/STARGATE_ATLANTIS_S2_D5/stargate.atlantis-s02e16.the_long_goodbye.VOB','STARGATE ATLANTIS S2 D5','stargate atlantis-s02e16 the long goodbye','video',0,0,0);

.quit
